services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    environment:
      APP_GREETING: "Hello from Compose"
      ConnectionStrings__Default: "Server=db,1433;Database=AppDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Pass123"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - backend

volumes:
  sql_data:

networks:
  backend:
    driver: bridge